config/routes.rb
Rails.application.routes.draw do

get 'seed_gen/index'

post 'organizations/:id/showvectors/' => 'organizations#showvectors'
post 'orgadmins/:id/showorgconnections/' => 'orgadmins#showorgconnections'
post 'orgadmins/:id/addorgconnections/' => 'orgadmins#addorgconnections'

get 'organizations/:id/showvectors/' => 'organizations#showvectors'
get 'orgadmins/:id/showorgconnections/' => 'orgadmins#showorgconnections'
get 'orgadmins/:id/addorgconnections/' => 'orgadmins#addorgconnections'
resources :organizations
get 'organizations/:id/about' => 'organizations#about'

resources :orgadmins

  devise_for :users, :controllers => {sessions: 'sessions', registrations: 'registrations'}
resources :logos do
  get "serve", :on => :member
end

  root 'organizations#index_landing'

end

app/controllers/orgadmins_controller.rb
class OrgadminsController < ApplicationController
  before_action :set_orgadmin, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  # GET /orgadmins
  # GET /orgadmins.json
  def index
    @organizations = Organization.all
  end

  # GET /orgadmins/1
  # GET /orgadmins/1.json
  def show
  end

  # GET /orgadmins/new
  def new
    @organization = Organization.new
  end

  # GET /orgadmins/1/edit
  def edit
    @orgs = Organization.all
    @logo = Logo.new
    @fundtypes = FundingType.all
  end

  # POST /orgadmins
  # POST /orgadmins.json
  def create
    @organization = Organization.new(orgadmin_params)

    respond_to do |format|
      if @organization.save
        format.html { redirect_to @organization, notice: 'Organization was successfully created.' }
        format.json { render :show, status: :created, location: @organization }
      else
        format.html { render :new }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orgadmins/1
  # PATCH/PUT /orgadmins/1.json
  def update
    respond_to do |format|
      if @organization.update(orgadmin_params)
        puts params[:name]
        puts @organization.name
        puts orgadmin_params
        format.html { redirect_to @organization, notice: 'Organization was successfully updated.' }
        format.json { render :show, status: :ok, location: @organization }
      else
        format.html { render :edit }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orgadmins/1
  # DELETE /orgadmins/1.json
  def destroy
    @organization.destroy
    respond_to do |format|
      format.html { redirect_to orgadmins_url, notice: 'Organization was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  # POST /orgadmins/1/showorgconnections
  def showorgconnections
    #@fundingsents = FundingSent.select('"orgrcvd".name, "funding_types".fundtype').from('"funding_sents" INNER JOIN "organizations" "orgrcvd" ON "orgrcvd"."id" = "funding_sents"."organization_id_received" INNER JOIN "organizations" "orgsent" ON "orgsent"."id" = "funding_sents"."organization_id_sent" INNER JOIN "funding_types" ON "funding_types"."id" = "funding_sents"."funding_type_id"').where("funding_sents.organization_id_sent = ?", params[:id])
    
    results = []
    sents = Organization.find(params[:id]).funding_sents
    froms = Organization.find(params[:id]).funding_receives
    
    sents.each do |funding_sent|
      results.push([funding_sent.organization_to.name, FundingType.find(funding_sent.funding_type_id).fundtype, 'Send', funding_sent.amount])
    end

    froms.each do |funding_from|
      results.push([funding_from.organization_from.name, FundingType.find(funding_from.funding_type_id).fundtype, 'Receive', funding_from.amount])
    end

    render :json => results
  end
  
  # POST /orgadmins/1/addconnection
  def addorgconnections
    
    if params[:send_receive] == 1
      org_from_id = params[:id]
      org_to_id = params[:sentto_id]
    else
      org_from_id = params[:sentto_id]
      org_to_id = params[:id]
    end
    fund_type = params[:fund_type]
    
    @fundingsent = FundingSent.new
    @fundingsent.organization_id_sent = org_from_id
    @fundingsent.organization_id_received = org_to_id
    @fundingsent.funding_type_id = params[:fund_type]
    @fundingsent.amount = params[:amount]
    
    if @fundingsent.save
      puts "funding save successful"
      render :json => {status: "success"}
    else
      puts "funding save failed"
      render(:status => 500)
    end
    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_orgadmin
      @organization = Organization.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def orgadmin_params
      params.permit(:name, :email, :address, :phone, :id, :descrip, :latitude, :longitude)
    end
end

app/helpers/orgadmins_helper.rb
module OrgadminsHelper
end

app/views/orgadmins/_form.html.erb
<%= form_for(@organization, :html => {class: "container form-horizontal"},url: { action: 'create', controller: 'orgadmins'})  do |f| %>
  <%= render 'formcontrols' %>
    <div class="form-group row">
    <%= link_to 'Back', orgadmins_path, class: "btn btn-warning" %>
    <%= f.submit "Save", class:"btn btn-success pull-right" %>
  </div>
<% end %>

app/views/orgadmins/_formcontrols.html.erb
<!-- the logo code will go here -->
		
			<!-- org name field/ Perhaps this can already be filled in? -->
			<div class="form-group row">
				<label class="control-label col-md-1" for="usr" >Name</label>
				<div class = "col-md-8">
				<input type="text" class="form-control" placeholder="Neighborhood Allies" name="name" value="<%= @organization.name %>">
				</div>
			</div>
			
			<!-- description stuff-->
			<div class="form-group row">
				<label class="control-label col-md-1" for="descrip" >Description</label>
				<div class = "col-md-8">
				<textarea class="form-control" placeholder="This is a great non-profit doing work in..." name="descrip"><%= @organization.descrip %></textarea>
				</div>
			</div>
			
			<!-- email -->
			<div class="form-group row">
				<label class="control-label col-md-1" for="email">Email</label>
				<div class = "col-md-8">
					<input type="email" class="form-control" placeholder="organization@email.com" name="email" value="<%= @organization.email %>">
				</div>
			</div>				
			
			<!-- phone number - don't forget to add the dashes and figure out how
				line up the beginning-->
			<div class="form-group row">	
				<label class="control-label col-md-1" style="padding-right: 0px" for="phone">Phone</label>
				<div class="col-md-4">
						<input type="tel" name="phone" class="form-control" value="<%= @organization.phone %>" size="12" maxlength="12" required="required" title="" placeholder="555-555-5555">
				</div>
			</div>
			
			<!-- address stuff-->
			<div class="form-group row">
				<label class="control-label col-md-1" for="address" >Address</label>
				<div class = "col-md-8">
				<textarea class="form-control" placeholder="555 Liberty Ave" name="address" onblur="getLatLong()" id="address"><%= @organization.address %></textarea>
				</div>
			</div>
			
			<div class="form-group row">
				<label class="control-label col-md-1" for="latlng">Lat/Long</label>
				<div class="col-md-2 form-latlng">
					<input type="text" class="form-control" placeholder="-79.99" name="latitude" id="latitude" value="<%= @organization.latitude %>" readonly>
				</div>
				<div class="col-md-2 form-latlng">
					<input type="text" class="form-control" placeholder="40.44" name="longitude" id="longitude" value="<%= @organization.longitude %>" readonly>
				</div>
			</div>


  <% if @organization.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@organization.errors.count, "error") %> prohibited this organization from being saved:</h2>

      <ul>
      <% @organization.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<script>
	function getLatLong(){
		$('.form-latlng').removeClass('has-success');
		$('.form-latlng').addClass('has-warning');
		$.getJSON('http://maps.googleapis.com/maps/api/geocode/json?address='+$('#address').val(), null, function (data) {
			if (data.results[0] == null){
			  $('.form-latlng').addClass('has-error');
			  $('.form-latlng').removeClass('has-warning');
			}
			else
			{
			  var addresslocation = data.results[0].geometry.location;
			  console.log(addresslocation);
			  $('#latitude').val(addresslocation.lat);
			  $('#longitude').val(addresslocation.lng);
			  $('.form-latlng').addClass('has-success');
			  $('.form-latlng').removeClass('has-warning');
			}
		});
	}
	
</script>

app/views/orgadmins/_formedit.html.erb
<%= form_for(@organization, :html => {class: "container form-horizontal"},url: "/orgadmins/" + @organization.id.to_s)  do |f| %>
  <%= render 'formcontrols' %>
    <div class="form-group row col-md-9">
    <%= link_to 'Back', orgadmins_path, class: "btn btn-warning" %>
    <%= f.submit "Submit", class:"btn btn-success pull-right" %>
  </div>
<% end %>

app/views/orgadmins/_logo.html.erb
<div class="modal fade" id="logomodal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Change Logo</h4>
      </div>
      <div class="modal-body">
        <%= form_for(@logo, :html => {:multipart => true, :id => "edit_logo"},
        				    :format => :json, 
        				    :url => "/logos/",
        				    :remote => true) do |f| %>
            <div class="field">
                <%= f.label 'Upload an Image' %>
                <%= f.file_field :data %>
            </div>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary" onClick="uploadPhoto()">Upload</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->


<script>
   function uploadPhoto(){
       console.log("starting upload");
       formData = new FormData()
       formData.append('logo', $('#logo_data')[0].files[0]);
       formData.append('organization_id', <%= @organization.id %>);
       formData.append('name', 'logo');
       console.log(formData);
        $.ajax({
            url: "/logos/",
            type: "POST",
            processData: false,
            contentType: false,
            //data: {logo: {data: $("#logo_data"), organization_id: $("#logo_organization_id"), name: $("#logo_data")}},
            data: formData,
            success: function (data) {
                console.log("Success!");
                $("#edit_logo_img").attr('src', '/logos/<%= @organization.id %>/serve?t='  + new Date().getTime());
                $('#logomodal').modal('hide');
            },
            error: function (xhr, status, err) {
                $('#logoerror').html('Error uploading your logo. Please try again.');
                console.log(status, err.toString());
            }
            
        })

        console.log("hello there!");
    }
</script>

app/views/orgadmins/_orgconnections.html.erb
<script>
  var orgconnections = [];

  function showorgconnections(id) {
   	$.post("/orgadmins/"+id+"/showorgconnections", function(data)
   	{
  	  
  	  orgconnections = data;
  	  var contentstring = '<thead><tr><th>Direction</th><th>Organization</th><th>Funding Type</th><th>Amount</td></tr></thead>';
  	  
  	  for (var i = 0; i < orgconnections.length; i++) {
  	    var orgconnection = orgconnections[i];
  	    var amount = '$' + orgconnection[3].toFixed(2).replace(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1,");
  	    
	      var line = {name: orgconnection[0], fundtype: orgconnection[1], direction: orgconnection[2], amount: amount};
	    
	      contentstring += '<tr><td>'+line.direction+'  </td><td>'+line.name+'</td><td>' + line.fundtype + '</td><td>' + line.amount + '</td></tr>';
  	  };
  	  
  	  document.getElementById("orgconnections").innerHTML = '<table class="table table-hover">'+contentstring+'</table>';
  	  
   	});
  }
   
  function addfundtype(organizationid) {
    sentto = $("#neworgconnectionname").val();
    fund_type = $("#neworgconnectionfundtype").val();
    send_receive = $("#sendreceive").val();
    amount = $("#amount").val();
    
    if (sentto != null && fund_type != null){
      $.ajax({
        method: "POST",
        url: "/orgadmins/"+organizationid+"/addorgconnections",
        data: {id: organizationid, sentto_id: sentto, fund_type: fund_type, send_receive: send_receive, amount: amount},
        })
        .success(function(data)
     	  {
     	      showorgconnections(organizationid);
     	  });
    }
    
    showorgconnections(organizationid); 
  }
  
  showorgconnections(<%= @organization.id %>); 
 </script>

<div class="container form-horizontal">

			<!-- Connections-->
			<div class="form-group row">
				<div class = "col-md-9">
			  	<div id="connections">
            <p id="orgconnections" class="orgconnections">
            </p>
          </div>
				</div>
			</div>

      <div class="form-group row">
          <label class="control-label col-md-1" for="neworgconnectionname" >Connecting Organization</label>
          <div class="col-md-8">
                <select name="neworgconnectionname" id="neworgconnectionname">
                  <option value="" selected="selected">Please select an organization to link to:</option>
                  <% @orgs.each do |organization| %>
                    <option value="<%= organization.id %>"><%= organization.name %></option>
                  <% end %>
                </select>
          </div>
      </div>

      <div class="form-group row">
        <label class="control-label col-md-1" for="neworgconnectionfundtype" >Funding Type</label>
        <div class="col-md-8">
          <select name="neworgconnectionfundtype" id="neworgconnectionfundtype">
            <option value="" selected="selected">Please select the finding type to link to the organization:</option>
            <% @fundtypes.each do |fundtype| %>
              <option value="<%= fundtype.id %>"><%= fundtype.fundtype %></option>
            <% end %>
          </select>
        </div>
      </div>
      
      <div class="form-group row">
        <label class="control-label col-md-1" for="sendreceive" >Send/Receive</label>
        <div class="col-md-8">
          <select name="sendreceive" id="sendreceive">
            <option value="1" selected="selected">Send</option>
            <option vlaue="2">Receive</option>
          </select>
        </div>
      </div>
      
			<div class="form-group row">
				<label class="control-label col-md-1" for="amount" >Amount</label>
				<div class = "col-md-8">
				<input type="text" class="form-control" placeholder="50000" name="amount" id="amount">
				</div>
			</div>

      <div class="form-group row">
        <div class="col-md-1"></div>
        <a onClick="addfundtype(<%= @organization.id %>);" href="#" class="btn btn-primary btn-md">Add Connection</a>
      </div>
</div>

app/views/orgadmins/edit.html.erb
<div class="col-md-8 col-md-offset-2">
    <div class="panel">
      <img id="edit_logo_img" src="/logos/<%= @organization.id %>/serve" style="padding: 15px;max-width: 200px; max-height: 200px"> 
<button type="button" class="btn btn-primary btn-md" data-toggle="modal" data-target="#logomodal">
  Update Logo
</button>
    <%= render 'formedit' %>
    <%= render 'logo' %>
  
    <%= render 'orgconnections' %>
    </div>

</div>

app/views/orgadmins/index.html.erb
<div class="col-xs-12 admin-body">
<div class="container col-md-2 columns"></div>
<div class="container col-md-8" style="background-color: white">
<ul class="list-unstyled">
  	<% @organizations.each do |organization| %>
	<li>
		<div class="list-group-item clearfix">
		<div class="pull-left">
		  <img src="/logos/<%= organization.id %>/serve" class="admin-logo">		
		</div>
		<div>
			<h3 class="list-group-item-heading title"><%= organization.name %></h3>
			<p class="list-group-item-text"><%= organization.descrip %></p>
		</div>
		<span class="pull-right">
			<%= link_to 'View',organization_path(organization), class: 'btn btn-info' %>
			<%= link_to 'Edit', edit_orgadmin_path(organization), class:"btn btn-warning" %>
			<button class= "btn btn-success">Connections</button>
			<!--<%= link_to 'Connections',organization_path(organization), class: 'btn btn-success' %> -->
			<%= link_to 'Suspend', "#", class:"btn btn-danger" %>
		</span>
		</div>
	</li>
	<% end %>
 </ul>
</div>
</div>

app/views/orgadmins/new.html.erb
<div class="col-md-8 col-md-offset-2">
  <div class="panel">
    <div class="panel-heading">New Organization</div>
      <div class="panel-body">
        <%= render 'form' %>
      </div>
  </div>
</div>

app/views/orgadmins/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_orgadmin_path(@orgadmin) %> |
<%= link_to 'Back', orgadmins_path %>